# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_largeClass', [dirname(__file__)])
        except ImportError:
            import _largeClass
            return _largeClass
        if fp is not None:
            try:
                _mod = imp.load_module('_largeClass', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _largeClass = swig_import_helper()
    del swig_import_helper
else:
    import _largeClass
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class largeClass(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, largeClass, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, largeClass, name)
    __swig_destroy__ = _largeClass.delete_largeClass
    __del__ = lambda self : None;
    def __init__(self, *args): 
        this = _largeClass.new_largeClass(*args)
        try: self.this.append(this)
        except: self.this = this
    def str(self): return _largeClass.largeClass_str(self)
    def readFromTextFile(self, *args): return _largeClass.largeClass_readFromTextFile(self, *args)
    def writeToTextFile(self, *args): return _largeClass.largeClass_writeToTextFile(self, *args)
    def readFromBinFile(self, *args): return _largeClass.largeClass_readFromBinFile(self, *args)
    def writeToBinFile(self, *args): return _largeClass.largeClass_writeToBinFile(self, *args)
    def __neg__(self): return _largeClass.largeClass___neg__(self)
    def __add__(self, *args): return _largeClass.largeClass___add__(self, *args)
    def __sub__(self, *args): return _largeClass.largeClass___sub__(self, *args)
    def __mul__(self, *args): return _largeClass.largeClass___mul__(self, *args)
    def __div__(self, *args): return _largeClass.largeClass___div__(self, *args)
    def __mod__(self, *args): return _largeClass.largeClass___mod__(self, *args)
    def __xor__(self, *args): return _largeClass.largeClass___xor__(self, *args)
    def __gt__(self, *args): return _largeClass.largeClass___gt__(self, *args)
    def __lt__(self, *args): return _largeClass.largeClass___lt__(self, *args)
    def __ne__(self, *args): return _largeClass.largeClass___ne__(self, *args)
    def __le__(self, *args): return _largeClass.largeClass___le__(self, *args)
    def __ge__(self, *args): return _largeClass.largeClass___ge__(self, *args)
    def __eq__(self, *args): return _largeClass.largeClass___eq__(self, *args)
    def __str__(self): return _largeClass.largeClass___str__(self)
    def __repr__(self): return _largeClass.largeClass___repr__(self)
largeClass_swigregister = _largeClass.largeClass_swigregister
largeClass_swigregister(largeClass)

def powModClass(*args):
  return _largeClass.powModClass(*args)
powModClass = _largeClass.powModClass

# This file is compatible with both classic and new-style classes.


